// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
 
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEGdO4q1G_7W3xJ_tR62nPbUliseiCS_k',
    appId: '1:410197167360:web:6de87b900f2b8dd657b7e5',
    messagingSenderId: '410197167360',
    projectId: 'marketingapp-c2e11',
    authDomain: 'marketingapp-c2e11.firebaseapp.com',
    storageBucket: 'marketingapp-c2e11.firebasestorage.app',
    measurementId: 'G-9PW1FBD87B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5_hU8tyUIB_tFCUWpYH9igOAHicVrvyg',
    appId: '1:410197167360:android:b00e3b201148abd157b7e5',
    messagingSenderId: '410197167360',
    projectId: 'marketingapp-c2e11',
    storageBucket: 'marketingapp-c2e11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu7AlEWf5piWG6F2bWmT0cD66In2kcJwU',
    appId: '1:410197167360:ios:52f8506f39e7b82157b7e5',
    messagingSenderId: '410197167360',
    projectId: 'marketingapp-c2e11',
    storageBucket: 'marketingapp-c2e11.firebasestorage.app',
    iosBundleId: 'com.example.marketapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu7AlEWf5piWG6F2bWmT0cD66In2kcJwU',
    appId: '1:410197167360:ios:52f8506f39e7b82157b7e5',
    messagingSenderId: '410197167360',
    projectId: 'marketingapp-c2e11',
    storageBucket: 'marketingapp-c2e11.firebasestorage.app',
    iosBundleId: 'com.example.marketapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEGdO4q1G_7W3xJ_tR62nPbUliseiCS_k',
    appId: '1:410197167360:web:d16315deb128e1c957b7e5',
    messagingSenderId: '410197167360',
    projectId: 'marketingapp-c2e11',
    authDomain: 'marketingapp-c2e11.firebaseapp.com',
    storageBucket: 'marketingapp-c2e11.firebasestorage.app',
    measurementId: 'G-RGFCM5E415',
  );
}
